### PR TITLE
Replace image URL from coingecko GetCoinMarkets reponse with our own …

### PR DESCRIPTION
**Pull request by nvonpentz**
…coingecko image proxy

### Summary

Addresses https://github.com/brave/brave-core/pull/12510#issuecomment-1203535924

### Type of change ( select one )

- [ ] Product feature
- [ ] Bug fix
- [ ] Performance improvement
- [ ] Refactor
- [ ] Other

### Tested Environments

- [ ] Development
- [ ] Staging
- [ ] Production

### Before submitting this PR:

- [ ] Does your code build cleanly without any errors or warnings?
- [ ] Have you used auto closing keywords?
- [ ] Have you added tests for new functionality?
- [ ] Have validated query efficiency for new database queries?
- [ ] Have documented new functionality in README or in comments?
- [ ] Have you squashed all intermediate commits?
- [ ] Is there a clear title that explains what the PR does?
- [ ] Have you used intuitive function, variable and other naming?
- [ ] Have you requested security / privacy review if needed
- [ ] Have you performed a self review of this PR?

### CODE REVIEW

**Review by kdenhartog — DISMISSED** [review]
LGTM thanks for getting this fix in

**Review by husobee — DISMISSED** [review]
LGTM, is the api.cgproxy.brave.com up and running?

**Review by husobee — DISMISSED** [review]

**Comment by nvonpentz** [comment]
api.cgproxy.brave.com is actually the wrong host, it should be assets.cgproxy.brave.com which is up and running - 
https://assets.cgproxy.brave.com/coins/images/17358/large/le1nzlO6_400x400.jpg?1632465691.  Implemented by devops here - https://github.com/brave/devops/issues/7563.  I updated the pull request, it should be good to go now.

**Review by husobee — APPROVED** [review]

**Comment by nvonpentz** [comment]
Looks good to me.  I would approve but can't since I opened the pull request.

**Review by husobee — APPROVED** [review]

**Pull request merged**
