### PR TITLE
(1) Include a JSON parser called payout_json_conversion_tool which

### PR DESCRIPTION
**Pull request by yachtcaptain23**
(1) Include a JSON parser called payout_json_conversion_tool which handles the incoming JSON for ads and publishers.
(2) Include Bearer token rather than Basic auth
(3) Support adsDirectDeposit
(4) Process bitflyer transactions to 8th decimal place
(5) Fix an issue when we try processing transactions to Bitflyer and
there's multiple transactions involved. We should merge all the bitflyer
transactions together. The lines involved for bitflyer/upload.go were
removed, as it's possible there's multiple payments to one channel, and
only one of these would succeed given that our transaction hashing algorithm
only takes in the channel and the payout_report_id.

Closes https://github.com/brave-intl/bat-go/issues/954

### CODE REVIEW

**Comment by amirsaber** [comment]
Recording
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x154f9c3]

goroutine 1 [running]:
github.com/brave-intl/bat-go/utils/clients.(*SimpleHTTPClient).Do(0x0, {0x1ccfed8, 0xc00011b380}, 0xc00015f500, {0x196b620, 0xc000590020})
        /Users/saber/code/bat-go/utils/clients/client.go:285 +0x83
github.com/brave-intl/bat-go/utils/clients/bitflyer.(*HTTPClient).UploadBulkPayout(0xc000118190, {0x1ccfed8, 0xc00011b380}, {0x0, {0xc000666a00, 0xfb, 0x110}, {0xc0000c2000, 0xb4}, 0x0})
        /Users/saber/code/bat-go/utils/clients/bitflyer/client.go:363 +0x146
github.com/brave-intl/bat-go/utils/clients/bitflyer.ClientWithPrometheus.UploadBulkPayout({{0x1cd5b38, 0xc000118190}, {0x1b69e4b, 0x19a36e0}}, {0x1ccfed8, 0xc00011b380}, {0x0, {0xc000666a00, 0xfb, 0x110}, ...})
        /Users/saber/code/bat-go/utils/clients/bitflyer/instrumented_client.go:105 +0x198
github.com/brave-intl/bat-go/settlement/bitflyer.SubmitBulkPayoutTransactions({0x1ccfed8, 0xc00011b380}, 0xc0002630b0, 0x24, 0xc0002630e0, {0x0, {0xc000666a00, 0xfb, 0x110}, {0xc0000c2000, ...}, ...}, ...)
        /Users/saber/code/bat-go/settlement/bitflyer/upload.go:118 +0x1af
github.com/brave-intl/bat-go/settlement/bitflyer.IterateRequest({0x1ccfed8, 0xc00011b380}, {0x1b60553, 0x6}, {0x1cd61b8, 0xc00025e6a0}, {0xc000114900, 0x1, 0xf}, {0x1b61be8, ...}, ...)
        /Users/saber/code/bat-go/settlement/bitflyer/upload.go:383 +0x6dd
github.com/brave-intl/bat-go/cmd/settlement.BitflyerUploadSettlement({0x1ccfed8, 0xc00011b380}, {0x1b60553, 0x6}, {0x7ffeefbff16c, 0x42}, {0xc000110000, 0x4b}, {0xc00005400f, 0x250}, ...)
        /Users/saber/code/bat-go/cmd/settlement/bitflyer.go:278 +0x231
github.com/brave-intl/bat-go/cmd/settlement.UploadBitflyerSettlement(0x23a1500, {0x7020102, 0x2, 0xc0004d1d48})
        /Users/saber/code/bat-go/cmd/settlement/bitflyer.go:110 +0x2be
github.com/brave-intl/bat-go/cmd.Perform.func1(0x23a1500, {0xc0001148a0, 0x1, 0x1})
        /Users/saber/code/bat-go/cmd/root.go:117 +0x52
github.com/spf13/cobra.(*Command).execute(0x23a1500, {0xc000114890, 0x1, 0x1})
        /Users/saber/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x239fc00)
        /Users/saber/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/saber/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /Users/saber/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:890
github.com/brave-intl/bat-go/cmd.Execute({0x1ca4bd0, 0x14}, {0x1ca1578, 0x7}, {0x1ca1dd0, 0xa})
        /Users/saber/code/bat-go/cmd/root.go:52 +0x31e
main.main()
        /Users/saber/code/bat-go/main.go:29 +0x45
```
on bitflyer upload, with retyring this goes through, we should capture the errors and recover gracefully

**Review by evq — CHANGES_REQUESTED** [review]
I think we should find a more permanent home for any parts of `payout_json_conversion_tool.py` that are actually needed. However I'm confused why most of that file is needed, from what I remember it shouldn't be.

e.g. `convert_publishers_file` seems superfluous, if you define wallet ids for each payout type in `~/.settlement.yaml` then the settlement tooling should operate directly on the combined input file and output split signed reports.

i'm also not sure how much of `convert_ads_file` is actually needed either. i'm pretty sure in the past I used the numbered settlement files directly out of antifraud.

**Comment by evq** [comment]
working on merging this piecemeal:
- [x] https://github.com/brave-intl/bat-go/pull/1049
- [x] https://github.com/brave-intl/bat-go/pull/1081
- [ ] support for `adsDirectDeposit` transaction types
- [ ] uphold forbidden error
- [ ] BF allowed transaction value mismatch tolerance
- [ ] cleanup gemini API ( base64 confusion )h

**Comment by evq** [comment]
closing as https://github.com/brave-intl/bat-go/pull/1156 has the last changes needed from this branch

**Pull request closed without merging**
