### PR TITLE
add support for uphold client credentials

### PR DESCRIPTION
**Pull request by amirsaber**
### Summary

Getting invalid token trying to upload uphold settlements

### Type of change ( select one )

- [ ] Product feature
- [x] Bug fix
- [ ] Performance improvement
- [ ] Refactor
- [ ] Other

### Tested Environments

- [ ] Development
- [ ] Staging
- [ ] Production

### Before submitting this PR:

- [ ] Does your code build cleanly without any errors or warnings?
- [ ] Have you used auto closing keywords?
- [ ] Have you added tests for new functionality?
- [ ] Have validated query efficiency for new database queries?
- [ ] Have documented new functionality in README or in comments?
- [ ] Have you squashed all intermediate commits?
- [ ] Is there a clear title that explains what the PR does?
- [ ] Have you used intuitive function, variable and other naming?
- [ ] Have you requested security / privacy review if needed
- [ ] Have you performed a self review of this PR?

### CODE REVIEW

**Review by evq — CHANGES_REQUESTED** [review]
i'm not sure we can apply this across the board. iirc we have two types of tokens in use:
1. legacy PAT ( used in grant service )
2. client credentials ( used for settlements )

i'm worried this will break 1. can we make this configurable?

**Comment by amirsaber** [comment]
> i'm worried this will break 1. can we make this configurable?
where is the right home for this configuration?

**Comment by amirsaber** [comment]
uphold team calls this a deprecated method, shall we update grants to follow latest?

**Comment by evq** [comment]
> > i'm worried this will break 1. can we make this configurable?
> 
> where is the right home for this configuration?

perhaps we could use separate env vars for PAT vs client credentials token? @husobee wdyt?

e.g. keep current `UPHOLD_ACCESS_TOKEN` for PAT and use `UPHOLD_CLIENT_CREDENTIALS_TOKEN` for client credentials?

> Uphold team calls the basic one - a deprecated method. shall we update grants to follow latest?

that'd be good, I would suggest that we defer and handle it as part of migrating the hot wallet functionality out of the grant server by using the nitro payments infra.g

**Comment by husobee** [comment]
I agree, lets use a seperate env variable for the "Bearer" style tokens.

**Review by husobee — APPROVED** [review]

**Review by evq — APPROVED** [review]

**Pull request merged**
